### ISSUE TITLE
FTP Server in AP Mode

### ISSUE THREAD

**Issue by bdespatis** [loboris/MicroPython_ESP32_psRAM_LoBo#25]
Hi,

I can only have a Ready FTP server if I use wlan in STA_IF mode and connect to my WiFi Network. Can we have it working when we are in AP_IF mode?

network.ftp.status()
(0, 0, 'Disabled', 'Data: Disconnected')

Thanks !

**Comment by Avi-TelnT** [comment]
FTP server is a WIFI device listen on IP:21 
When it connects to your local router, it must be in STA mode,  so you can access it from any device connected to the same local WIFI router, like from your PC for development. 
In AP, it acts as a router, and you will have a problem to connect to it from your router since your router is AP too. And AP does not connect to other AP. 
In WIFI only STA connected to AP. 
So: in AP only other ESP32 in STA can access it. Is that what you really need? 

Since in any case, ESP32 FTP server can use only on development since you never can penetrate router from the internet (NAT blocking). 
So, ESP32 connect to a router, cannot be accessed from the internet for a firmware data update. 
In AP in router mode, it has no internet access anyway.  
To solve this limitation, we need an ESP32 in STA to connect to the internet FTP as a client, and auto downloads a new firmware parodically.....

If this parodically FTP client scan is not the desired connection. And we like to command the ESP32 behind a NAT router we need on the internet **a switching server** that will bridge a command from the internet to ESP32 behind a NAT.....
If someone likes to develop this, send me a message, avi@telnt.com

**Comment by bdespatis** [comment]
I was looking for the same feature as Pycom to have an Access Point to start an FTP and send script over WiFi.

**Comment by Avi-TelnT** [comment]
If ESP will be configured as AP. You can't connect to it over your local WIFI router. 
AP will not connect to other AP.
If you use laptop with WIFI, you can disconnect its WIFI from your router, and make new connection to ESP as AP router, and then you can call its ESP IP:21
In that time you will lose all internet link off-course.

**Comment by bdespatis** [comment]
Yes, I know, but I can't access IP:21 if the ftp is disconnected. My point is the ftp.start() doesn't work when I am in AP mode at all. I tried to connect FileZilla (working OK with STA) when my computer is connected to the ESP in AP mode. I can make it work if I use the ftp.py from [https://github.com/robert-hh/ESP8266-FTP-Server/blob/master/ftp.py](url)

**Comment by loboris** [comment]
@bdespatis 
There was a bug in ftp server which prevented connection in AP mode.
It is fixed now, I've tested it and it works without problem.
The updates will be commited tomorow.
I,m sorry, it was my error, thank you for noticing.

@Avi-TelnT
If ESP32 is connected in STA mode it can be quite easily accessed over Internet if you configure port forwarding on your router.

**Comment by Avi-TelnT** [comment]
Port forwarding is not an option for something you like to work anywhere. 
Also, UPnP will not work. 
The only way to penetrate NAT router is by switching server on the internet. 
If you interested, I can guide to build one as part of your great ESP32 projects.

**Comment by loboris** [comment]
@bdespatis
Sorry, the changes are not pushed yet, there were some problems/bugs in other modules I'm testing.
I expect to finish today, and the changes will be pushed tomorrow.

**Comment by loboris** [comment]
The update is now pushed, ftp server in AP mode works.
```
>>> import network                                                                                                                          
I (29326) phy: phy_version: 362.0, 61e8d92, Sep  8 2017, 18:48:11, 0, 0                                                                     
>>> router = network.WLAN(network.AP_IF)                                                                                                    
>>> router.active(True)                                                                                                                     
True                                                                                                                                        
>>> router.ifconfig()                                                                                                                       
('192.168.4.1', '255.255.255.0', '192.168.4.1', '0.0.0.0')                                                                                  
>>> network.ftp.start()                                                                                                                     
True                                                                                                                                        
>>> network.ftp.status()                                                                                                                    
(2, 0, 'Ready', 'Data: Disconnected')                                                                                                       
>>> network.ftp.status()                                                                                                                    
(7, 0, 'Connected', 'Data: Disconnected')                                                                                                   

```
