### ISSUE TITLE
ESP32 WROOM Erratic Behaviour

### ISSUE THREAD

**Issue by diginfo** [loboris/MicroPython_ESP32_psRAM_LoBo#29]
I am testing a ESP32 WROOM and are experiencing some strange errors:

During boot I get:

`Possibly invalid CONFIG_ESP32_XTAL_FREQ setting (40MHz). Detected 40 MHz`

So it's set to 40mhz and 40mhz is detected - why the error ?

And when I import my wlan connection (which works no problem on esp8266, ESP32 Thing & LOLIN) I get a phy_init error followed by a brownout.

But a brownout is impossible as the brownout voltage is 2.1 volts and I am using a good quality 5 Amp bench power supply, I am 100% sure there's no problem with the power ?!

```
>>> import wlan
W (16368) phy_init: failed to load RF calibration data (0x1102), falling back to full calibration

Brownout detector was triggered

ets Jun  8 2016 00:22:57
```

**Comment by loboris** [comment]
The first is [known bug in esp-idf](https://www.esp32.com/viewtopic.php?f=13&t=3340&p=15636&hilit=Possibly+invalid+CONFIG_ESP32_XTAL_FREQ#p15636).

The `Brownout detector was triggered` is most certainly caused by bad power supply (from ESP32 chip's point of view).
A very short drop in power supply may cause the brownout reset.
The source can be USB port, USB cable, the board USB connector, the board's LDO...
You may try to add a 100~470 uF capacitor between +3.3 & GND on your board.
