### ISSUE TITLE
FTP server doesn't get/put files?

### ISSUE THREAD

**Issue by carterw** [loboris/MicroPython_ESP32_psRAM_LoBo#36]
I enabled the FTP server in the firmware build menu. I seem to be able to log on to the FTP server ok (after connecting the ESP32 to my local WiFi network of course) using the default username/password but then I can't list files or move them to or from the device;

# on esp32;
>>> import network
>>> network.ftp.start()
True

# on an Ubuntu machine;
$ ftp 192.168.1.246
Connected to 192.168.1.246.
220 Micropython FTP Server

# then logged on with micro/python

ftp> ls
502
ftp: bind: Address already in use
ftp> put afile.txt
local: afile.txt remote: afile.txt
502

**Comment by Avi-TelnT** [comment]
in my tests, it works OK. 
Look at MicroPython_ESP32_psRAM_LoBo/MicroPython_BUILD/components/micropython/esp32/libs/ftp.h
You must use :  user: micro pass: python
See
#define FTP_DEF_USER            "micro"
#define FTP_DEF_PASS            "python"
I get the main.py
change it to main_test.py
and put it over FTP
I used FTP app

**Comment by loboris** [comment]
@carterw
Please, see the Notes in [the documentation](https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/blob/master/MicroPython_BUILD/components/micropython/docs/servers.md)

> Only one data connection can be used, make shure your FTP client does not try to establish multiple data connections

On Ubuntu I'm using Caja file manager and with it ftp connection to MicroPython works without problem.
[screenshot](http://loboris.eu/ESP32/Screenshot_11.png)

**Comment by Avi-TelnT** [comment]
@loboris 
FTP is working perfectly. 
But see the challenge: ESP32 with FTP will be always behind wifi router NAT.
Since only router has an access to internet over ADSL or cables. 
So, the ESP32 FTP can't be accessed from any FTP client from the internet. 
Router port forwarding is not a real option for worldwide deployment. 
So the ESP32 FTP can be used only for development when it is in your home/office/lab inner network. 
To solve that, we need to do something called a "bridge". 
Do you like to speak about that? 
Please call my boss Skype: nissim.test he did that for VOIP voice chat before. 
My boss Dr. Nissim Zur will be in Berlin from 21-Nov-2017 for few 4 days. He will be happy to meet you.

**Comment by loboris** [comment]
@Avi-TelnT
Accessing servers behind NAT is common problem, not related to MicroPython implementation.
I have my own solutions to that problem which works well (I'm often accessing the Internet via GSM and there is always the NAT problem), it would be interesting to hear more about yours. At the moment I don't have enough free time to work on this, but thanks for the offer.
BDW, I do not live in Berlin.

**Comment by carterw** [comment]
ftp working here when started in passive mode. Thanks!
