### ISSUE TITLE
file removed from frozen module remains in firmware

### ISSUE THREAD

**Issue by carterw** [loboris/MicroPython_ESP32_psRAM_LoBo#92]
As I understand it, copying module directories into the MicroPython_BUILD/components/micropython/esp32/modules directory causes them to be frozen into the firmware.

I removed a file from one of my module directories there, performed "./BUILD.sh clean", and then "./BUILD.sh all". Erased and reflashed the firmware on my ESP32 and the 'removed' file is still in the firmware.

Maybe the 'clean' step is not cleaning out all of the residues of previous builds? Or or the compile step is not taking into account the current contents of the modules directory?

**Comment by loboris** [comment]
`./BUILD.sh clean` completely removes the `MicroPython_BUILD/build` directory so there can be no traces from previously built components and frozen modules.

The frozen modules are compiled from the content of the `MicroPython_BUILD/components/micropython/esp32/modules` directory.

If you remove something from the `MicroPython_BUILD/components/micropython/esp32/modules` directory there is no way it will be compiled and included in the firmware, simply because there is no source to build from.
